#!/bin/sh

mkdir -p opk
cp ./drally_linux opk/drally_linux
cp ./icon.png opk/icon.png
cp ./LICENSE opk/COPYRIGHT
cp ./MANUAL opk/MANUAL.txt

# https://unix.stackexchange.com/questions/219268/how-to-add-new-lines-when-using-echo
print()
	case    ${IFS- } in
	(\ *)   printf  %b\\n "$*";;
	(*)     IFS=\ $IFS
	printf  %b\\n "$*"
	IFS=${IFS#?}
esac

# Create GmenuNx entry file plus other things

print '[Desktop Entry]
Type=Application
Name=Death Rally
Comment=Needs data !
Exec=drally_linux
Icon=icon
Terminal=false
Type=Application
X-OD-NeedsJoystick=true
Categories=games;
X-OD-Manual=MANUAL.txt;
' > opk/default."$1".desktop

mksquashfs ./opk deathrally_"$1".opk -all-root -noappend -no-exports -no-xattrs

rm -r opk
